export type Labels = {
  min: string,
  max: string,
  step: string,
  div: string,
  mod: string,
  close: string,
  help:string,
  open: string,
  infoTitle: string,
  index: string,
  value: string,
  divValue: string,
  modValue: string,
  sortInstruction: string,
  errorMsg: string,
  resetDefaults: string,
  cancelSorts: string,
}
export const heLabels: Labels = {
  min: 'מינימום',
  max: 'מקסימום',
  step: 'הפרש',
  div: 'חלוקה',
  mod: 'שארית',
  close: 'סגור',
  help: 'עזרה',
  open: 'פתח',
  infoTitle: 'מה הטבלה מציגה?',
  index: '#',
  value: 'ערך',
  divValue: 'ערך חלקי X',
  modValue: 'X מודולו ערך',
  sortInstruction: 'לחץ על כותרת העמודה הרלוונטית כדי למיין לפי הערך המיוצג על ידי העמודה.',
  errorMsg: 'אי אפשר לחלק באפס.',
  resetDefaults: 'חזרה לערכים התחלתיים',
  cancelSorts: 'בטל את כל המיונים',
}
export const enLabels: Labels = {
  min: 'Min',
  max: 'Max',
  step: 'Step',
  div: 'Div',
  mod: 'Mod',
  close: 'Close',
  help: 'Help',
  open: 'Open',
  infoTitle: 'What does this table show?',
  index: '#',
  value: 'Value',
  divValue: 'Div Value by X',
  modValue: 'Mod X by Value',
  sortInstruction: 'Click on any column header to sort the results by the header\'s relative value.',
  errorMsg: 'One cannot divide by zero.',
  resetDefaults: 'Clear to default values',
  cancelSorts: 'Cancel all sorts',
}
